Subject.create([
  {subject: "Economics"},
  {subject: "Chemistry"},
  {subject: "Geography"},
  {subject: "Biology"},
  {subject: "Physics"},
  {subject: "Literature"},
  {subject: "Mathematics"},
  {subject: "History"},
  {subject: "General Paper"}
])

SeabTopic.create(
  [
    {subject_id:"1", topic: "Market System", description:"This theme provides an introduction to the nature of economics and examines the operation of markets for goods and services. It also focuses on how consumers and producers make decisions about the choices they face, recognising that in the market economy, both are motivated by self-interest. You should be able to understand the price mechanism as a means of allocating resources and be able to apply demand and supply analysis to real world situations."},
    {subject_id:"1", topic: "Market Failure and Government Intervention", description:"This theme examines the nature of market failure, its causes and possible policy remedies. You should be able to understand why markets may not allocate resources efficiently and the methods of dealing with market failure, together with an evaluation of their effectiveness."},
    {subject_id:"1", topic: "National and International Economy", description: "This theme provides an introduction to the key indicators of economic performance, the basic AD/AS and AE-Income analysis, and  the main objectives and instruments of government policy. You should be able to acquire a good knowledge of recent economic trends and developments in Singapore and the international economy. You should also be able to appreciate the possible underlying causes of these trends and developments and to evaluate the effectiveness of government policies in the light of these events."},
    {subject_id:"5", topic: "Measurement", description: "In this prelude to actual physics, the Measurement theme provides a sound foundation to the mathematical work of physics. Here, SI Units are introduced along with their accessory prefixes and suffixes, the errors and uncertainties that may occur in a measurement delineated, and scalars and vectors described."},
    {subject_id:"5", topic: "Newtonian Mechanics", description:"Newtonian mechanics serves as the de facto introduction to classical physics. Here, we explore kinematics and dynamics, forces and their resulting work done, energy, and power. Circular motion and gravitation are explained, and rounded off with oscillatory phenomena."},
    {subject_id:"5", topic: "Thermal Physics", description: "Thermal physics concerns itself with the internal energy of materials, in latent heat and heat capacities. You will learn of the different temperature scales and the thermodynamic temperature's connection to a molecule's kinetic energy, the 1st law of thermodynamics, and the ideal gas equation."},
    {subject_id:"5", topic: "Waves", description:"Waves underpin the bulk of physical phenomena. This theme explains wave motion, and the superposition of waves, which will help you to understand the many and varied intricacies of higher level physics."},
    {subject_id:"5", topic: "Electricity and Magnetism", description:"The E&M theme explores electric fields, electric currents, and direct current (D.C.) circuits. It then goes on to reveal the Januslike nature of E&M, EM induction, and finally to talk about alternating current (A.C.) circuits."},
    {subject_id:"5", topic: "Modern Physics", description: "The Modern Physics theme provides an overview to the advancements in physics in the 20th century, and beyond. Here, you will receive a primer on the weirdness of quantum mechanics, its applications to lasers and semiconductors, and unlock the many secrets of the atomic nucleus."},
    {subject_id:"7", topic: "Pure Mathematics", description: "This theme explores abstract concepts in Mathematics, such as theorems proofs and equations"},
    {subject_id:"7", topic: "Statistics", description: "This theme introduces basic mechanisms in Statistics, such as the different types of distributions and methods of analysis"},
    {subject_id:"4", topic: "How Life Works", description: "This theme examines the basis of life and basic cellular processes. You should be able to understand how cells reproduce, function, and use a wide range of chemical processes to maintain homeostasis within the cellular environment"},
    {subject_id:"4", topic: "Understanding the Diversity of Organisms", description: "This theme explores the kingdoms and their respective subdivisons. It focuses on the differences between organisms and families of organisms. It also examines the theories behind evolution and the speciation of organisms"},
    {subject_id:"4", topic: "Relevance to Oneself and Society", description: "This theme provides an introduction to the applications of Biology in the real world. It introduces methods used in genetic engineering and molecular biology"},
    {subject_id:"9", topic: "Paper 1: Essay", description: "Among twelve different essay prompts, GP students have to choose one and express their views in a critical and creative manner. Here, we will be sharing tips and strategies pertinent to writing a good argumentative essay."},
    {subject_id:"9", topic: "Paper 2: Comprehension", description: "Paper 2 comprises of comprehension questions, a summary and an application question. The goal is to assess how well you are able to explain, infer, evaluate and summarise information from a given passage. We will be covering the various skills required to tackle these types of questions in the following lectures"}
  ]
)

SeabSubTopic.create(
  [
    { topic: "Scarcity, Choice and Opportunity Cost", seab_topic_id: "1" },
    { topic: "Resource Allocation in Competitive Markets", seab_topic_id: "1"},
    { topic: "Firms and How They Operate" , seab_topic_id: "1"},
    { topic: "Market Failure", seab_topic_id: "2" },
    { topic: "Government Intervention in The Market", seab_topic_id: "2" },
    { topic: "Key Economic Indicators", seab_topic_id: "3" },
    { topic: "How The Macroeconomy Works", seab_topic_id: "3" },
    { topic: "International Economics", seab_topic_id: "3" },
    { topic: "Measurement", seab_topic_id: "4" },
    { topic: "Kinematics", seab_topic_id: "5" },
    { topic: "Dynamics", seab_topic_id: "5" },
    { topic: "Forces", seab_topic_id: "5" },
    { topic: "Work, Energy and Power", seab_topic_id: "5" },
    { topic: "Motion in a Circle", seab_topic_id: "5" },
    { topic: "Gravitational Field", seab_topic_id: "5" },
    { topic: "Oscillations", seab_topic_id: "5" },
    { topic: "Thermal Physics", seab_topic_id: "6" },
    { topic: "Wave Motion", seab_topic_id: "7" },
    { topic: "Superposition", seab_topic_id: "7" },
    { topic: "Electric Fields", seab_topic_id: "8" },
    { topic: "Current of Electricity", seab_topic_id: "8" },
    { topic: "D.C. Circuits", seab_topic_id: "8" },
    { topic: "Electromagnetism", seab_topic_id: "8" },
    { topic: "Electromagnetic Induction", seab_topic_id: "8" },
    { topic: "Alternating Currents", seab_topic_id: "8" },
    { topic: "Quantum Physics", seab_topic_id: "9" },
    { topic: "Lasers and Semiconductors", seab_topic_id: "9" },
    { topic: "Nuclear Physics", seab_topic_id: "9" },
    { topic: "Functions and Graphs", seab_topic_id: "10" },
    { topic: "Sequences and Series", seab_topic_id: "10" },
    { topic: "Vectors", seab_topic_id: "10" },
    { topic: "Complex Numbers", seab_topic_id: "10" },
    { topic: "Calculus", seab_topic_id: "10" },
    { topic: "Permutations, Combinations and Probability", seab_topic_id: "11" },
    { topic: "Binomial, Poisson and Normal Distributions", seab_topic_id: "11" },
    { topic: "Correlation and Regression", seab_topic_id: "11" },
    { topic: "Cellular Functions", seab_topic_id: "12" },
    { topic: "DNA & Genomics", seab_topic_id: "12" },
    { topic: "Genetics of Viruses and Bacteria", seab_topic_id: "12" },
    { topic: "Organisation & Control of Prokaryotic & Eukaryotic Genomes", seab_topic_id: "12" },
    { topic: "Genetic Basis for Variation", seab_topic_id: "12" },
    { topic: "Cellular Physiology and Biochemistry", seab_topic_id: "12" },
    { topic: "Diversity and Evolution", seab_topic_id: "13" },
    { topic: "Isolating, Cloning and Sequencing DNA", seab_topic_id: "14" },
    { topic: "Applications of Molecular and Cell Biology", seab_topic_id: "14" },
    { topic: "Writing a GP Essay", seab_topic_id: "15" },
    { topic: "Tackling GP Paper 2", seab_topic_id: "16" }
  ]
)


Topic.create(
  [
    { topic: "Introduction to Economics and Scarcity", subject_id:"1", seab_sub_topic_id:"1" },
    { topic: "Demand and Supply", subject_id:"1",seab_sub_topic_id:"1"},
    { topic: "Elasticities", subject_id:"1",seab_sub_topic_id:"1"},
    { topic: "Theory of the Firm", subject_id:"1", seab_sub_topic_id:"2" },
    { topic: "Alternative Theories of the Firm", subject_id:"1", seab_sub_topic_id:"2" },
    { topic: "Market Structure", subject_id:"1", seab_sub_topic_id:"2" },
    { topic: "Price Discrimination", subject_id:"1", seab_sub_topic_id:"2" },
    { topic: "Efficiency of Different Market Structures", subject_id:"1", seab_sub_topic_id:"2" },
    { topic: "Market Failure", subject_id:"1", seab_sub_topic_id:"3" },
    { topic: "Government Intervention", subject_id:"1", seab_sub_topic_id:"4" },
    { topic: "Microeconomics Case Studies", subject_id:"1", seab_sub_topic_id:"4" },
    { topic: "Key Economic Indicators", subject_id:"1", seab_sub_topic_id:"5" },
    { topic: "Standard of Living", subject_id:"1", seab_sub_topic_id:"6" },
    { topic: "Main Macroeconomic Goals", subject_id:"1", seab_sub_topic_id:"6" },
    { topic: "National Income, Aggregate Demand and Supply, National Expenditure", subject_id:"1", seab_sub_topic_id:"7" },
    { topic: "Fiscal Policy", subject_id:"1", seab_sub_topic_id:"7" },
    { topic: "Monetary Policy", subject_id:"1", seab_sub_topic_id:"7" },
    { topic: "Exchange Rate Policy", subject_id:"1", seab_sub_topic_id:"7" },
    { topic: "Supply Side Policies", subject_id:"1", seab_sub_topic_id:"7" },
    { topic: "Globalisation", subject_id:"1", seab_sub_topic_id:"8" },
    { topic: "International Trade", subject_id:"1", seab_sub_topic_id:"8" },
    { topic: "Interconnectedness of Macroeconomic Issues", subject_id:"1", seab_sub_topic_id:"8" },
    { topic: "Kinematics", subject_id:"5",seab_sub_topic_id:"9"},
    { topic: "Angles, Triangles and Polygons", subject_id:"7",seab_sub_topic_id: "31" },
    { topic: "DNA Replication", subject_id:"4",seab_sub_topic_id:"38" },
    { topic: "Stem Cells", subject_id:"4",seab_sub_topic_id:"45"},
    { topic: "Argumentation", subject_id:"9",seab_sub_topic_id:"46" }
  ]
)


Lesson.create(
  [
    {lesson: "Scarcity and Choice",topic_id: "1"},
    {lesson: "Opportunity Cost",topic_id: "1"},
    {lesson: "You Demand",topic_id: "2"},
    {lesson: "I Supply",topic_id: "2"},
    {lesson: "The Markets",topic_id: "2"},
    {lesson: "Shifts",topic_id: "2"},
    {lesson: "Concept of Elasticity",topic_id: "3"},
    {lesson: "Price Elasticity of Demand",topic_id: "3"},
    {lesson: "Cross Elasticity of Demand",topic_id: "3"},
    {lesson: "Income Elasticity of Demand",topic_id: "3"},
    {lesson: "Price Elasticity of Supply",topic_id: "3"},
    {lesson: "Factors of Production and Time",topic_id: "4"},
    {lesson: "Production in the Short Run",topic_id: "4"},
    {lesson: "Costs in the Short Run",topic_id: "4"},
    {lesson: "Long Run Theory of Production",topic_id: "4"},
    {lesson: "Costs in the Long Run",topic_id: "4"},
    {lesson: "Revenue",topic_id: "4"},
    {lesson: "Profit Maximisation",topic_id: "4"},
    {lesson: "Problems with Traditional Theory",topic_id: "5"},
    {lesson: "Alternative Maximising Theories",topic_id: "5"},
    {lesson: "Multiple Aims in a Firm",topic_id: "5"},
    {lesson: "In the Real World",topic_id: "5"},
    {lesson: "Features of the Market Structures",topic_id: "6"},
    {lesson: "Perfect Competition",topic_id: "6"},
    {lesson: "Monopoly",topic_id: "6"},
    {lesson: "Monopolistic Competition",topic_id: "6"},
    {lesson: "Oligopoly",topic_id: "6"},
    {lesson: "Introduction to Price Discrimination",topic_id: "7"},
    {lesson: "First Degree Price Discrimination",topic_id: "7"},
    {lesson: "Second Degree Price Discrimination",topic_id: "7"},
    {lesson: "Third Degree Price Discrimination",topic_id: "7"},
    {lesson: "Applications of Price Discrimination",topic_id: "7"},
    {lesson: "Recap on Efficiency",topic_id: "8"},
    {lesson: "Allocative Efficiency",topic_id: "8"},
    {lesson: "Productive Efficiency",topic_id: "8"},
    {lesson: "Evaluating Market Structures",topic_id: "8"},
    {lesson: "What is Market Failure",topic_id: "9"},
    {lesson: "Externalities",topic_id: "9"},
    {lesson: "Merit and Demerit Goods",topic_id: "9"},
    {lesson: "Public Goods",topic_id: "9"},
    {lesson: "Imperfect Competition",topic_id: "9"},
    {lesson: "Information and Mobility",topic_id: "9"},
    {lesson: "Summary and Looking Forward",topic_id: "9"},
    {lesson: "Who's Your Daddy",topic_id: "10"},
    {lesson: "Taxes and Subsidies",topic_id: "10"},
    {lesson: "Direct Provision",topic_id: "10"},
    {lesson: "Legislation and Regulation",topic_id: "10"},
    {lesson: "Nationalisation",topic_id: "10"},
    {lesson: "Privitisation and Deregulation",topic_id: "10"},
    {lesson: "Income Equality",topic_id: "10"},
    {lesson: "Government Failure",topic_id: "10"},
    {lesson: "Inflation",topic_id: "12"},
    {lesson: "Unemployment",topic_id: "12"},
    {lesson: "GDP",topic_id: "12"},
    {lesson: "Balance of Payments",topic_id: "12"},
    {lesson: "Material and Non-Material Wellbeing",topic_id: "13"},
    {lesson: "Question Analysis",topic_id: "13"},
    {lesson: "Varying Unemployment",topic_id: "14"},
    {lesson: "Bad Inflation",topic_id: "14"},
    {lesson: "Actual and Potential Growth",topic_id: "14"},
    {lesson: "BOP Deficits and Surpluses",topic_id: "14"},
    {lesson: "The Circular Flow of Income",topic_id: "15"},
    {lesson: "Aggregate Demand",topic_id: "15"},
    {lesson: "Aggregate Supply",topic_id: "15"},
    {lesson: "Equilibrium Level of Output and Price",topic_id: "15"},
    {lesson: "The Multiplier Effect",topic_id: "15"},
    {lesson: "Basic Fiscal Policy",topic_id: "16"},
    {lesson: "The Mechanisms of Fiscal Policy",topic_id: "16"},
    {lesson: "Correcting a Recession",topic_id: "16"},
    {lesson: "Stabilising Inflation",topic_id: "16"},
    {lesson: "Correcting a Trade Deficit",topic_id: "16"},
    {lesson: "Evaluations",topic_id: "16"},
    {lesson: "Interest Rates",topic_id: "17"},
    {lesson: "Money Neutrality",topic_id: "17"},
    {lesson: "Monetary Policy",topic_id: "17"},
    {lesson: "Evaluation",topic_id: "17"},
    {lesson: "Additional Topics in Monetary Policy",topic_id: "17"},
    {lesson: "The Exchange Rate",topic_id: "18"},
    {lesson: "Exchange Rate Systems",topic_id: "18"},
    {lesson: "Exchange Rate and The Balance of Payments",topic_id: "18"},
    {lesson: "Exchange Rate Policy in Singapore",topic_id: "18"},
    {lesson: "Product Market-Oriented Policies",topic_id: "19"},
    {lesson: "Labour Market-Oriented Policies",topic_id: "19"},
    {lesson: "Interventionist",topic_id: "19"},
    {lesson: "The Aftermath",topic_id: "19"},
    {lesson: "Introduction to Globalisation",topic_id: "20"},
    {lesson: "Impact of Globalisation",topic_id: "20"},
    {lesson: "Evaluating Different Countries",topic_id: "20"},
    {lesson: "Why We Trade",topic_id: "21"},
    {lesson: "The Winners and Losers",topic_id: "21"},
    {lesson: "Post-Ricardian Trade Theories",topic_id: "21"},
    {lesson: "Trade Policy",topic_id: "21"},
    {lesson: "Displacement, Velocity and Acceleration",topic_id: "23"},
    {lesson: "Kinematic Equations",topic_id: "23"},
    {lesson: "Angles",topic_id: "24"},
    {lesson: "Polygons",topic_id: "24"},
    {lesson: "Construction",topic_id: "24"},
    {lesson: "Similarity and Congruence",topic_id: "24"},
    {lesson: "Replication",topic_id: "25"},
    {lesson: "Transcription",topic_id: "25"},
    {lesson: "Translation",topic_id: "25"},
    {lesson: "Introduction to Stem Cells",topic_id: "26"},
    {lesson: "Gene Therapy",topic_id: "26"},
    {lesson: "Counterargument",topic_id: "27"}
  ]
)
