Subject.create(subject: "Economics")
SeabTopic.create(subject_id: "1", topic: "Market System", description: "lol")
SeabSubTopic.create(seab_topic_id: "1", topic: "Demand and Supply")
Topic.create(subject_id:"1", seab_sub_topic_id: "1", topic: "Hello", description: "Hello")
Lesson.create(topic_id: "1", lesson: "Supply Shifts", user_id: "1")
Checkpoint.create(lesson_id: "1", checkpoint: "Supply checkpoint", description: "lolol", videourl: "yolourl", objective: "complete the yolo")
